#! /bin/sh

# Fail immediately on errors
set -e

# Display commands as they execute
set -x

compile_css() {
  local stylus=./node_modules/.bin/stylus
  find ./<%= pkg %>/<%= STATIC_DIR_NAME %> -type f -name *.styl | \
  xargs $stylus --compress --sourcemap --use ./node_modules/nib/lib/nib
}

compile_css
./node_modules/.bin/webpack -p --devtool source-map
